hb_stats/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'(?P<code>\w+)/', include('humblebola.urls'))
]

humblebola/urls.py
from django.conf.urls import url, include

from . import views

player_patterns = [
    url(r'^$',
        views.player_home_page,
        name="player_home_page"),
    url(r'(?P<player_id>[\d]+)-[\w]+-[\w]+/',
        views.player_page,
        name="player_page")
]

tournament_patterns = [
    url(r'^$',
        views.schedule,
        name="schedule")
]

team_tournament_patterns = [
    url(r'^$',
        views.team_tournament_page,
        name="tournament_page"),
    url(r'games/',
        views.team_schedule_page,
        name="schedule"),
    url(r'game_log',
        views.team_tournament_game_log,
        name="game_log"),
]
team_patterns = [
    url(r'(?P<team_code>[\w-]+)/', include([
        url(r'^$',
            views.team_index_page,
            name="index"),
        url(r'(?P<tournament_id>[\d]+)/', include(team_tournament_patterns,
            namespace="tournament")
            ),
        ], namespace="team")),
]

urlpatterns = [
    url(r'^$', views.home_page, name="home_page"),
    url(r'tournaments/', include(
        tournament_patterns, namespace="tournaments")),
    url(r'teams/', include(team_patterns, namespace="teams")),
    url(r'players/', include(player_patterns, namespace="players"))
]

hb_stats/templates/base.html
{% load staticfiles %}
{% load main_nav_tags %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/layout.css' %}">
</head>
<body>

{# same header for everything #}
<header>
    <nav id="hb-top-nav">
        <ul>
            <a href="{% url 'home_page' league.code %}"><li>Home</li></a>
            <a href="http://humblebola.com/advanced-stats-primer/"><li>Advanced Stats 101</li></a>
            {% show_leagues league %}
        </ul>
        <ul>
            <a href="https://www.facebook.com/HumbleBola/"><li>Facebook</li></a>
            <a href="https://twitter.com/HumbleBola_"><li>Twitter</li></a>
        </ul>
    </nav>
    <nav id="hb-main-nav">
        <ul>
            <a href="{% url 'tournaments:schedule' league.code %}"><li>Scores & Schedule</li></a>
            <li><a href="#">Teams</a>
            <ul>{% show_teams league %}</ul>
            </li>
            <a href="{% url 'players:player_home_page' league.code %}"><li>Players</li></a>
        </ul>
    </nav>
</header>
=======================================
{% block content %}{% endblock content %}
=======================================
<footer>
    <ul>
        <li>About</li>
        <li>Contact Us</li>
        <p>&copy; 2016 HumbleBola</p>
    </ul>
</footer>
</body>
</html>

hb_stats/templates/base_team.html
{% extends "base.html" %}
{% load team_nav_tags %}

{% block content %}
    <h1>{{ team.team_name }} {{ team.nickname }} Roster and Stats</h1>
    <h2>{{ tournament.name }}</h2>
    {% team_nav_bar %}
=======================================
{% block section %}
{% endblock %}

{% endblock %}

hb_stats/templates/leagues.html
{% for league in leagues %}
    <a href="{% url 'home_page' league.code %}"><li>{{ league.short_name }} Stats</li></a>
{% endfor %}


hb_stats/templates/team_nav_bar.html
<a href="{% url 'teams:team:index' league.code team.code %}"><p>Team Index Page</p></a>
{% if previous_tournament_link %}
    <a href="{{ previous_tournament_link }}"><p><< {{ previous_tournament.name }}</p></a>
{% endif %}
{% if next_tournament_link %}
    <a href="{{ next_tournament_link }}"><p>{{ next_tournament.name }} >></p></a>
{% endif %}
<ul>
<li>Seasons
    {% if league.id == 1 %}
        {% regroup tournaments_table by tournament.parent.short_name as tournament_list %}
        <ul>
        {% for tournament in tournament_list %}
            {% if tournament.grouper %}
                <li>{{ tournament.grouper }}
                <ul>
                    {% for item in tournament.list %}
                        <li><a href="{% url 'teams:team:tournament:tournament_page' league.code team.code item.tournament.id %}">{{ item.tournament.short_name }}</a></li>
                    {% endfor %}
                </ul>
                </li>
            {% endif %}
        {% endfor %}
        </ul>
    {% else %}
        <ul>
        {% for item in tournaments_table %}
            <li><a href="{% url 'teams:team:tournament:tournament_page' league.code team.code item.tournament.id %}">{{ item.tournament.short_name }}</a></li>
        {% endfor %}
        </ul>
    {% endif %}
</li>
<li>Roster & Stats
    <ul>
        <li><a href="{% url 'teams:team:tournament:tournament_page' league.code team.code current_tournament.id %}#roster">Roster</a></li>
        <li><a href="{% url 'teams:team:tournament:tournament_page' league.code team.code current_tournament.id %}#team_stats">Team & Opponent Stats</a></li>
        <li><a href="{% url 'teams:team:tournament:tournament_page' league.code team.code current_tournament.id %}#players_totals">Players: Totals</a></li>
        <li><a href="{% url 'teams:team:tournament:tournament_page' league.code team.code current_tournament.id %}#players_per_game">Players: Per Game</a></li>
        {% if league.id == 1 %}
            <li><a href="{% url 'teams:team:tournament:tournament_page' league.code team.code current_tournament.id %}#players_per_x_min">Players: Per 36 Min</a></li>
        {% else %}
            <li><a href="{% url 'teams:team:tournament:tournament_page' league.code team.code current_tournament.id %}#players_per_x_min">Players: Per 30 Min</a></li>
        {% endif %}
    </ul>
</li>
<li><a href="{% url 'teams:team:tournament:schedule' league.code team.code current_tournament.id %}">Schedule and Results</a></li>
<li>Others
    <ul>
        <li><a href="{% url 'teams:team:tournament:game_log' league.code team.code current_tournament.id %}">Game Log</a></li>
        <li>Starting Lineups</li>
    </ul>
</li>
</ul>
<p>Record: {{ record.win }}-{{ record.loss }}</p>
<p>ORTG: {{ ortg }}</p>
<p>DRTG: {{ drtg }}</p>

hb_stats/templates/teams.html
{% for team in teams|dictsort:'team_name' %}
    <a href="{% url 'teams:team:index' league.code team.code %}"><li>{{ team.team_name }} {{ team.nickname }}</li></a>
{% endfor %}
